import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import RF from "react-native-responsive-fontsize"

module.exports = {
    COLOR: {
      ORANGE:'#ffa400',
      GRAY: '#999999',
      BLACK:"#444444",
      ShadowColor: 'rgb(220,220,220)',
      input_color:"rgb(201,201,201)",
      backgroundColor: "white",   
      fontfamily: "Muli-Bold",
      FontFamilyBold:"Muli-ExtraBold",
      rootBAckgroundColor:"rgb(243,242,242)",
      White_color:"white",
      Font_bold:"Muli-ExtraBold",
      Font:"Muli-Bold",
      width:290,
      _width : 330,
       _height : 2,
       Logo_width:94,
       Logo_height:65,
       Icon_divider_width:3,
       Icon_divider_height:23,
       Icon_width:25,
       Yellow_60:60,
       Size_75 :75,size_10:10,size_7:7,
       Size_15:15,Size_14:14,
       Size_60:60,Size_13:13,
       Size_35:35,Size_8:8,size_5:5,size_120:120,
       Size_100:100,Size_16:18,Size_27:27,size_200:200,Size_20:20,size_160:160,
    },
    Header:{fontWeight: 'bold',marginBottom:hp("2%"),fontSize: RF("2.4"),justifyContent:"center",alignItems:"center"
  },
    Logo : require('../Image/icon/logo_3.png'),
    rectangle_image : require('../Image/icon/Line/rectangle1.png'),
    Copy_right : require('../Image/icon/copyright.png'),
    rectangle_image_black : require('../Image/main/tableDivider2x.png'),
    Unchecked : require('../Image/new_images/uncheckedIcon3x.png'),
    Checked : require('../Image/new_images/selectedIcon3x.png'),
    Cancel_Button : require('../Image/icon/cancel1.png'),
    Accept : require('../Image/main/acceptIcon3x.png'),
    Reject : require('../Image/main/rejectIcon3x.png'),
    Serve_time : require('../Image/main/serveTimeIcon3x.png'),
    Date_icon : require('../Image/main/dateIcongray3x.png'),
    TAb_image_yellow : require('../Image/main/highlight3x.png'),
    TAb_image_transparent : require('../Image/main/line-transparent-vertical-2.png'),
    Notification_yellow : require('../Image/new_images/notificationIcon3x.png'),
    Notification_Gray : require('../Image/new_images/activenotificationIcon3x_2.png'),
    Star : require('../Image/new_images/emptyStar3x.png'),
    Location_icon : require('../Image/new_images/locationIcon2x.png'),
    Edit_icon : require('../Image/new_images/editAddressIcon2x.png'),
    Search_icon : require('../Image/new_images/searchIcon2x.png'),
    table_divider : require('../Image/main/tableDivider2x.png'),
    Down_Arrow : require('../Image/new_images/downArrow2x.png'),
    Filter_Icon : require('../Image/new_images/filterIcon3x.png'),
    rectangle_image : require('../Image/new_images/rectangle1_3x.png'),
    back_icon : require('../Image/icon/back_2x.png'),
    plus_icon : require('../Image/icon/plus.png'),
    edit_icon : require('../Image/main/editButton3x.png'),
    Arro : require('../Image/icon/arrow_right.png'),
    call_icon : require('../Image/new_images/callIcon3x.png'),
    Divider : require('../Image/new_images/divider13x.png'),
    salon_icon : require('../Image/new_images/salonIcon3x.png'),
    Doctor : require('../Image/new_images/doctorIcon3x.png'),
    Restaurent : require('../Image/new_images/restaurantIcon3x.png'),
    Unselect_Icon : require('../Image/main/unselectedIcon3x.png'),
    Select_Icon : require('../Image/main/selectedIcon3x.png'),
    Edit_Icon : require('../Image/main/editButtonmain3x.png'),
  };